---
#- hosts: webservers
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_user: vagrant
    ansible_ssh_pass: vagrant
    http_scheme: http
    http_host: 0.0.0.0
    http_port: 8000
    php_version: 7.3
  remote_user: vagrant
  tasks:
    - name: Adding php repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - unzip
        state: latest
        update_cache: true

    - name: Install PHP {{ php_version | default("7.3")}}
      apt:
        name:
          - php{{php_version}}
          - php{{php_version}}-mbstring
          - php{{php_version}}-dom
          - php{{php_version}}-zip
        state: latest
        update_cache: true

    - name: Composer download installer
      get_url:
        url: https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer
        dest: /home/vagrant/
    - name: Composer run installer
      command: runuser -u vagrant -- php -q /home/vagrant/installer
    - name: Delete composer installer
      file:
        state: absent
        path: /home/vagrant/installer
    - name: Check if project directory already exist
      stat:
        path: /home/vagrant/project
      register: project_folder_stat
    - name: Run composer create project
      become_user: vagrant
      command: php composer.phar create-project laravel/laravel project
      when: project_folder_stat.stat.exists == False

#    - name: Run artisian web server
#      become_user: vagrant
#      shell:
#        cmd: php project/artisan serve --host {{http_host}} --port {{http_port}} &> artisian_serve.log&
#        chdir: /home/vagrant/

#    - name: Check if server available
#      uri:
#        url: "{{http_scheme}}://{{http_host}}:{{http_port}}/"
#        method: GET
#        return_content: no
#        status_code: 200
